using Game.World.Generation;


namespace Game.World.Biomes.Surface
{
    /// <summary>
    /// Kept for source compatibility.
    /// Surface flora is no longer written into Chunk foreground.
    /// It is generated by SurfaceFloraFurnitureGenerator directly
    /// into FurnitureLayerManager after save changes are applied.
    /// </summary>
    public static class SurfaceFloraPostProcessor
    {
        public static void ApplyToChunk(
            WorldGenerator generator,
            WorldSettings settings,
            Chunk chunk
        )
        {
            // Intentionally empty.
        }
    }
}
